fix typo in Workflow Submission mutation
IndicoDataSolutions/indico-client-csharp pull request #21
Opened 2020-10-20 17:52 UTC by fitzworkhub

2020-10-20 18:04 UTC, nkassis approved these changes

2020-10-21 06:12 UTC, addy419 approved these changes

2020-10-21 09:24 UTC, addy419 requested changes
Variables need to be changed in the response too. I will be addressing these changes further in the next PR for submissions and workflows

```
string jobId = (string)response.Data.workflowSubmission.jobId;
 if (jobId == null)
{
       throw new RuntimeException($"Failed to submit to workflow {this.Id}");
}

return new Job(this._client.GraphQLHttpClient, jobId);
```

2021-01-25 10:22 UTC, addy419 commented
Resolved in cd47520b392685cc3f1fb878b8d77d86ce54db5b

2021-01-25 10:22 UTC, closed without merging